<template>
  <div class="button" title="settings" v-on:click="clickButton">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 32">
    <title></title>
    <g id="icon-pencil"></g>
    <path d="M27 0c2.761 0 5 2.239 5 5 0 1.126-0.372 2.164-1 3l-2 2-7-7 2-2c0.836-0.628 1.874-1 3-1zM2 23l-2 9 9-2 18.5-18.5-7-7-18.5 18.5zM22.362 11.362l-14 14-1.724-1.724 14-14 1.724 1.724z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'stage-sides-buttonsbar-edit',
  methods: {
    clickButton: function () {
      console.log('@stage_dataset.sides.buttonsBar.edit: clickButton')
      this.$emit('clickButton')
    }
  }
}
</script>

<style scoped>
.button {
  background-color: transparent;
  border-radius: 15%;
  display: inline-block;
  float: left;
  height: 16px;
  margin: 2px 4px 2px 4px;
  stroke-width: 0;
  width: 16px;
}
.button:active {
  background-color: gray;
}
.button:hover {
  cursor: pointer;
}
.button:hover > .icon {
  fill: rgb(255, 255, 255);
  transition: background 0.2s ease-in-out;
}
.icon {
  display: inline-block;
  fill: rgb(200, 200, 200);
  height: 14px;
  margin: 1px;
  stroke-width: 0;
  width: 14px;
}
</style>
