<template>
  <div class="button" title="settings" v-on:click="clickButton">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 32">
    <title></title>
    <g id="icon-download3"></g>
    <path d="M23 14l-8 8-8-8h5v-12h6v12zM15 22h-15v8h30v-8h-15zM28 26h-4v-2h4v2z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'stage-sides-buttonsbar-import',
  methods: {
    clickButton: function () {
      console.log('@stage_dataset.sides.buttonsBar.import: clickButton')
      this.$emit('clickButton')
    }
  }
}
</script>

<style scoped>
.button {
  background-color: transparent;
  border-radius: 15%;
  display: inline-block;
  float: left;
  height: 16px;
  margin: 2px 4px 2px 4px;
  stroke-width: 0;
  width: 16px;
}
.button:active {
  background-color: gray;
}
.button:hover {
  cursor: pointer;
}
.button:hover > .icon {
  fill: rgb(255, 255, 255);
  transition: background 0.2s ease-in-out;
}
.icon {
  display: inline-block;
  fill: rgb(200, 200, 200);
  height: 14px;
  margin: 1px;
  stroke-width: 0;
  width: 14px;
}
</style>
