<template>
  <div class="button" v-on:click="tabClick" v-bind:class="{active_class: this.selected === this.$props.current_tab}" title="visualization">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 32">
      <title></title>
      <g id="stats-dots"></g>
      <path d="M4 28h28v4h-32v-32h4zM9 26c-1.657 0-3-1.343-3-3s1.343-3 3-3c0.088 0 0.176 0.005 0.262 0.012l3.225-5.375c-0.307-0.471-0.487-1.033-0.487-1.638 0-1.657 1.343-3 3-3s3 1.343 3 3c0 0.604-0.179 1.167-0.487 1.638l3.225 5.375c0.086-0.007 0.174-0.012 0.262-0.012 0.067 0 0.133 0.003 0.198 0.007l5.324-9.316c-0.329-0.482-0.522-1.064-0.522-1.691 0-1.657 1.343-3 3-3s3 1.343 3 3c0 1.657-1.343 3-3 3-0.067 0-0.133-0.003-0.198-0.007l-5.324 9.316c0.329 0.481 0.522 1.064 0.522 1.691 0 1.657-1.343 3-3 3s-3-1.343-3-3c0-0.604 0.179-1.167 0.487-1.638l-3.225-5.375c-0.086 0.007-0.174 0.012-0.262 0.012s-0.176-0.005-0.262-0.012l-3.225 5.375c0.307 0.471 0.487 1.033 0.487 1.637 0 1.657-1.343 3-3 3z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'tab-visualization',
  data () {
    return {
      selected: `this.$props.current_tab`
    }
  },
  props: ['current_tab'],
  methods: {
    tabClick: function () {
      console.log('@tab_button.visualization: tabClick')
      this.selected = 'visualization'
      this.$emit('tabClick', {stage: 'visualization'})
    }
  }
}
</script>

<style scoped>
.active_class {
  background-color: rgb(55, 55, 55);
}
.button {
  display: block;
  float: right;
  height: 36px;
  margin: 0;
  stroke-width: 0;
  width: 40px;
}
.button {
  user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -o-user-select: none;
}
.button:hover {
  background-color: yellow;
  cursor: pointer;
  transition: background 0.3s ease-in-out;
}
.button:active {
  background-color: rgb(55, 55, 55);
}
.icon {
  display: block;
  fill: gray;
  height: 20px;
  margin: 8px 10px;
  stroke: rgb(80,80,80);
  stroke-width: 0;
  width: 20px;
}
</style>
