<template>
  <div class="button" v-on:click="tabClick" :class="{active_class: this.selected === this.$props.current_tab}" title="aquisition">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 32">
      <title></title>
      <g id="icon-download"></g>
      <path d="M16 18l8-8h-6v-8h-4v8h-6zM23.273 14.727l-2.242 2.242 8.128 3.031-13.158 4.907-13.158-4.907 8.127-3.031-2.242-2.242-8.727 3.273v8l16 6 16-6v-8z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'tab-aquisition',
  data () {
    return {
      selected: `this.$props.current_tab`
    }
  },
  props: ['current_tab'],
  methods: {
    tabClick: function () {
      console.log('@tab_button.aquisition: tabClick')
      this.selected = 'aquisition'
      this.$emit('tabClick', {stage: 'aquisition'})
    }
  }
}
</script>

<style scoped>
.active_class {
  background-color: rgb(55, 55, 55);
}
.button {
  display: block;
  float: right;
  height: 36px;
  margin: 0;
  stroke-width: 0;
  width: 40px;
}
.button {
  user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -o-user-select: none;
}
.button:hover {
  background-color: yellow;
  cursor: pointer;
  transition: background 0.3s ease-in-out;
}
.button:active {
  background-color: rgb(55, 55, 55);
}
.icon {
  display: block;
  fill: gray;
  height: 20px;
  margin: 8px 10px 8px 10px;
  stroke: rgb(80,80,80);
  stroke-width: 0;
  width: 20px;
}
</style>
