<template>
  <div class="button" title="settings" v-on:click="clickButton">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 36">
    <title></title>
    <g id="icon-cross">
    </g>
    <path d="M31.708 25.708c-0-0-0-0-0-0l-9.708-9.708 9.708-9.708c0-0 0-0 0-0 0.105-0.105 0.18-0.227 0.229-0.357 0.133-0.356 0.057-0.771-0.229-1.057l-4.586-4.586c-0.286-0.286-0.702-0.361-1.057-0.229-0.13 0.048-0.252 0.124-0.357 0.228 0 0-0 0-0 0l-9.708 9.708-9.708-9.708c-0-0-0-0-0-0-0.105-0.104-0.227-0.18-0.357-0.228-0.356-0.133-0.771-0.057-1.057 0.229l-4.586 4.586c-0.286 0.286-0.361 0.702-0.229 1.057 0.049 0.13 0.124 0.252 0.229 0.357 0 0 0 0 0 0l9.708 9.708-9.708 9.708c-0 0-0 0-0 0-0.104 0.105-0.18 0.227-0.229 0.357-0.133 0.355-0.057 0.771 0.229 1.057l4.586 4.586c0.286 0.286 0.702 0.361 1.057 0.229 0.13-0.049 0.252-0.124 0.357-0.229 0-0 0-0 0-0l9.708-9.708 9.708 9.708c0 0 0 0 0 0 0.105 0.105 0.227 0.18 0.357 0.229 0.356 0.133 0.771 0.057 1.057-0.229l4.586-4.586c0.286-0.286 0.362-0.702 0.229-1.057-0.049-0.13-0.124-0.252-0.229-0.357z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'header-tablist-item-close',
  methods: {
    clickButton: function () {
      console.log('@tab_item.closeButton: clickButton')
      this.$emit('clickButton')
    }
  }
}
</script>

<style scoped>
.button {
  background-color: rgb(80, 80, 80);
  border-radius: 50%;
  display: inline-block;
  float: right;
  height: 18px;
  margin: 5px 5px;
  stroke-width: 0;
  width: 18px;
}
.button {
  user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -o-user-select: none;
}
.button:hover {
  background-color: rgb(184, 62, 62);
  cursor: pointer;
  stroke: red;
}
.button:active {
  background-color: gray;
}
.icon {
  display: inline-block;
  fill: rgb(255,255,255);
  height: 12px;
  stroke: rgb(80,80,80);
  stroke-width: 3px;
  width: 12px;
}
</style>
