<template>
  <div class="button" title="settings">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 34 30">
    <title></title>
    <g id="icomoon-ignore">
    </g>
    <path d="M14 4v-0.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18zM8 8v-4h4v4h-4zM26 13.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-18v4h18v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h6v-4h-6v-0.5zM20 18v-4h4v4h-4zM14 23.5c0-0.825-0.675-1.5-1.5-1.5h-5c-0.825 0-1.5 0.675-1.5 1.5v0.5h-6v4h6v0.5c0 0.825 0.675 1.5 1.5 1.5h5c0.825 0 1.5-0.675 1.5-1.5v-0.5h18v-4h-18v-0.5zM8 28v-4h4v4h-4z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'header-button-settings'
}
</script>

<style scoped>
.button {
  background-color: rgb(90,90,90);
  border-radius: 2px;
  display: inline-block;
  float: right;
  height: 24px;
  margin: 3px 5px;
  stroke-width: 0;
  width: 50px;
}
.button {
  user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -o-user-select: none;
}
.button:hover {
  background-color: yellow;
  cursor: pointer;
}
.button:active {
  background-color: gray;
}
.icon {
  display: inline-block;
  fill: rgb(0,0,0);
  height: 22px;
  stroke: rgb(80,80,80);
  stroke-width: 0;
  width: 22px;
}
</style>
