<template>
  <div class="button" title="settings" v-on:click="clickButton">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 32">
    <title></title>
    <g id="icon-plus">
    </g>
    <path d="M31 12h-11v-11c0-0.552-0.448-1-1-1h-6c-0.552 0-1 0.448-1 1v11h-11c-0.552 0-1 0.448-1 1v6c0 0.552 0.448 1 1 1h11v11c0 0.552 0.448 1 1 1h6c0.552 0 1-0.448 1-1v-11h11c0.552 0 1-0.448 1-1v-6c0-0.552-0.448-1-1-1z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'stage-sides-buttonsbar-add',
  methods: {
    clickButton: function () {
      console.log('@stage_dataset.sides.buttonsBar.add: clickButton')
      this.$emit('clickButton')
    }
  }
}
</script>

<style scoped>
.button {
  background-color: rgb(200, 200, 200);
  border-radius: 50%;
  display: inline-block;
  float: left;
  height: 16px;
  margin: 2px 4px 2px 4px;
  stroke-width: 0;
  width: 16px;
}
.button:active > .icon {
  fill: gray;
}
.button:hover {
  background-color: rgb(255, 255, 255);
  cursor: pointer;
  transition: background 0.2s ease-in-out;
}
.icon {
  display: inline-block;
  fill: rgb(40, 40, 40);
  height: 8px;
  margin: 4px 4px;
  stroke-width: 0;
  width: 8px;
}
</style>
