<template>
  <div class="button" title="overview">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 32">
    <title></title>
    <g id="icon-equalizer">
    </g>
    <path d="M0 26h32v4h-32zM4 18h4v6h-4zM10 10h4v14h-4zM16 16h4v8h-4zM22 4h4v20h-4z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'button-overview'
}
</script>

<style scoped>
.button {
  background-color: rgb(90,90,90);
  border-radius: 2px;
  display: inline-block;
  float: right;
  height: 24px;
  margin: 3px 5px;
  stroke-width: 0;
  width: 50px;
}
.button {
  user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -o-user-select: none;
}
.button:hover {
  background-color: yellow;
  cursor: pointer;
}
.button:active {
  background-color: gray;
}
.icon {
  display: inline-block;
  fill: rgb(0,0,0);
  height: 22px;
  stroke: rgb(80,80,80);
  stroke-width: 0;
  width: 22px;
}
</style>
