<template>
  <div class="button" title="settings">
    <!-- Generated by IcoMoon.io -->
    <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 32 36">
    <title></title>
    <g id="icon-plus">
    </g>
    <path d="M31 12h-11v-11c0-0.552-0.448-1-1-1h-6c-0.552 0-1 0.448-1 1v11h-11c-0.552 0-1 0.448-1 1v6c0 0.552 0.448 1 1 1h11v11c0 0.552 0.448 1 1 1h6c0.552 0 1-0.448 1-1v-11h11c0.552 0 1-0.448 1-1v-6c0-0.552-0.448-1-1-1z"></path>
    </svg>
  </div>
</template>

<script>
export default {
  name: 'tablist-item-add'
}
</script>

<style scoped>
.button {
  background-color: rgb(90,90,90);
  border-radius: 2px 50% 0 50%;
  display: inline-block;
  float: right;
  height: 22px;
  margin: 5px 5px 2px 5px;
  opacity: 0.55;
  stroke-width: 0;
  width: 20px;
}
.button {
  user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -o-user-select: none;
}
.button:hover {
  background-color: green;
  cursor: pointer;
  opacity: 1;
  stroke: red;
}
.button:active {
  background-color: gray;
}
.icon {
  display: inline-block;
  fill: rgb(255,255,255);
  height: 12px;
  margin-top: 6px;
  stroke: rgb(80,80,80);
  stroke-width: 3px;
  width: 12px;
}
</style>
